services:
  - type: web
    name: imageexplorermonkey
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    autoDeploy: true
    healthCheckPath: /